export const REQUEST_CONTENT_PENDING='REQUEST_ROBOTS_PENDING';
export const REQUEST_CONTENT_SUCCESS='REQUEST_ROBOTS_SUCCESS';
export const REQUEST_CONTENT_FAILED='REQUEST_ROBOTS_FAILED';

export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';

export const START_VOICE_RECORDING='START_VOICE_RECORDING';
export const STOP_VOICE_RECORDING='STOP_VOICE_RECORDING';
export const REQUEST_TRANSCRIPTION_PENDING='REQUEST_TRANSCRIPTION_PENDING';
export const REQUEST_TRANSCRIPTION_SUCCESS='REQUEST_TRANSCRIPTION_SUCCESS';
export const REQUEST_TRANSCRIPTION_FAILED='REQUEST_TRANSCRIPTION_FAILED';